name: nmp-multi-publish
on:
  workflow_dispatch:
  push:
    paths:
      - "bin/**"
      - "src/**"
      - ".env.example"
      - "README.md"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/nmp-multi-publish.yml"
permissions:
  id-token: write # Required for OIDC
  contents: read
  packages: write
jobs:
  nmp-multi-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
      - run: |
          npm i
          npm i -g @tltdh61/dotenvrtdb
          npm i -g @o861runners/nmp
      - name: Check npm package files
        run: npm pack --dry-run
      - name: Publish to multi-registry
        env:
          DOTENVRTDB_URL: ${{ secrets.DOTENVRTDB_URL }}
          NPM_TOKEN_O2516PM0510: ${{ secrets.NPM_TOKEN_O2516PM0510 }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dotenvrtdb --eUrl "$DOTENVRTDB_URL" -- nmp publish
